version: '3.8'

services:
 api:
  build:
   context: ./backend/
  ports:
  - 5000:5000
  env_file:
  - .dev.env
  volumes:
  - ./backend/:/app

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  env_file:
  - .dev.env
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

 frontend:
   build:
     context: ./frontend/
   ports:
   - 8080:8080

volumes:
  mysql:
  mysql_config:
