version: '3.8'

services:
 # api:
 #  build:
 #   context: ./backend/
 #  ports:
 #  - 8000:8000
 #  env_file:
 #  - .dev.env
 #  depends_on:
 #    - mysqldbgame
 #  volumes: ['./backend:/app']

 mysqldbgame:
  image: postgres
  container_name: "psqldbgame"
  restart: always
  ports:
  - 5432:5432
  env_file:
  - .dev.env
