version: '3.8'

services:
 api:
  build:
   context: ./backend/
  ports:
  - 5000:5000
  env_file:
  - .dev.env
  volumes:
  - .:/backend/
  networks:
    - local-net
  depends_on:
    - mysqldb

 mysqldb:
  image: mysql
  # container_name: "mysqldb"
  restart: always
  ports:
  - 3306:3306
  env_file:
  - .dev.env
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql
  networks:
  - local-net

 frontend:
   build:
     context: ./frontend/
   ports:
   - 8080:8080

volumes:
  mysql:
  mysql_config:

networks:
  local-net:
    driver: bridge
