version: '3.8'

services:
 api:
  build:
   context: ./backend/
  ports:
  - 5000:5000
  env_file:
  - .dev.env
  networks:
    - local-net
  depends_on:
    - mysqldbgame

 mysqldbgame:
  image: mysql
  # container_name: "mysqldb"
  restart: always
  ports:
  - 3306:3306
  env_file:
  - .dev.env
  volumes:
  - mysqlgame:/var/lib/mysql
  - mysql_configgame:/etc/mysql
  networks:
  - local-net

 frontend:
   build:
     context: ./frontend/
   ports:
   - 8080:8080

volumes:
  mysqlgame:
  mysql_configgame:

networks:
  local-net:
    driver: bridge
