version: '3.8'

services:
 api:
  build:
    context: ./
  ports:
  - 8000:8000
  env_file:
  - .dev.env
  depends_on:
    - mysqldbgame
  volumes:
    - type: bind
      source: ./app
      target: /app
      read_only: true

 mysqldbgame:
  image: postgres
  container_name: "psqldbgame"
  restart: always
  ports:
  - 3306:5432
  env_file:
  - .dev.env

volumes:
  app:
