name: Deploy Prod

# -----
# This workflow will run whenever changes are pushed to main
# -----

on:
  push:
    branches:
      - main
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: ${{ secrets.SSH_PORT }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
jobs:
  deploy:
    name: Deploy
    environment: prod
    runs-on: ubuntu-latest
    steps:
      # -----
      # Allow this instance spun up by github to SSH into our vps
      # -----
      - uses: actions/download-artifact@v2
      - name: Copy bleck into id rsa
        run: install -m 600 -D /dev/null ~/.ssh/id_rsa
      - name: See if env vars propagated
        run: echo "$SSH_HOST"
      - name: Copy private key into keyfile
        run: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - name: Scan into known hosts
        run: ssh-keyscan -H -p "$SSH_PORT" "$SSH_HOST" > ~/.ssh/known_hosts
      - name: make some oflder
        run: mkdir send
      - name: record source
        run: ls -al > send/home.txt
      - name: record pwd
        run: pwd > send/home2.txt
      - name: Grab source
        run: rsync -rav --delete -e 'ssh -p 3732'  send/  "$SSH_USERNAME"@"$SSH_HOST":/home/"$SSH_USERNAME"/src/game-remix-guesser-backend/
