name: Deploy Prod

# -----
# This workflow will run whenever changes are pushed to main
# -----

on:
  push:
    branches:
      - main
env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_PORT: ${{ secrets.SSH_PORT }}
jobs:
  deploy:
    name: Deploy
    environment: prod
    runs-on: ubuntu-latest
    steps:
      # -----
      # Allow this instance spun up by github to SSH into our vps
      # -----
      - uses: actions/download-artifact@v2
      - name: Copy bleck into id rsa
        run: install -m 600 -D /dev/null ~/.ssh/id_rsa
      - name: See if env vars propagated
        run: echo "$SSH_HOST"
      - name: Copy private key into keyfile
        run: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - name: Scan into known hosts
        run: ssh-keyscan -H "$SSH_HOST" > ~/.ssh/known_hosts
      - name: Grab source
        run: rsync -rav --delete -e 'ssh -p "$secrets.SSH_PORT"' build/"$secrets.SSH_USERNAME"@"$secrets.SSH_HOST":/src/game-remix-guesser-backend/
